# Generated by Django 4.0.6 on 2022-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_provider_city_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_products', models.CharField(max_length=25, verbose_name='Products name')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='products',
            field=models.ManyToManyField(to='catalog.products'),
        ),
    ]
